domain: example.com
url: https://example.com

title: Muhash
email: wind@example.com
author: Muhammed Ashfar

lang: en
baseurl: ''

plugins:
  - jekyll-seo-tag

# disqus:
#   shortname: example-com
#
# rrss:
  # discord: hoola
  # facebook: hola
  # twitter: Hola
  # instagram: Hola
  # linkedin: Hola
  # pinterest: hola
  # whatsapp: 123
  # telegram: 123
  # email: email
