domain: https://muhashfar.github.io/PersonalPortfolio
url: https://muhashfar.github.io/PersonalPortfolio

title: Muhash
email: muhammedashfar@hotmail.com
author: Muhammed Ashfar

lang: en
baseurl: ''

collections:
  posts:
    output: true
    permalink: /:title

plugins:
  - jekyll-seo-tag

# disqus:
#   shortname: example-com
#
rrss:
 # discord: ''
 # facebook: hola
 twitter: 'https://twitter.com/_muhash'
 instagram: 'https://www.instagram.com/_muhash/'
 # linkedin: ''
 # pinterest: ''
 whatsapp: 'https://wa.me/919496659631?text=hey%20%3A)%0A'
 # telegram: ''
 email: muhammedashfar@hotmail.com
