# Domain
domain: https://muhashfar.github.io/PersonalPortfolio
url: https://muhashfar.github.io/PersonalPortfolio

# Info
title: Muhash
email: muhammedashfar@hotmail.com
author: Muhammed Ashfar

# Language
lang: en

# Baseurl
baseurl: ''

# Collections
collections:
  posts:
    output: true
    permalink: /:title
  feeds:
    output: true


plugins:
  - jekyll-seo-tag

# disqus:
#   shortname: example-com


rrss:
 # discord: ''
 # facebook: hola
 twitter: 'https://twitter.com/_muhash'
 instagram: 'https://www.instagram.com/_muhash/'
 # linkedin: ''
 # pinterest: ''
 whatsapp: 'https://wa.me/918848403432?text=hey%20%3A)%0A'
 # telegram: ''
 email: muhammedashfar@hotmail.com

defaults:
  # You can use the following to enable comments on all posts.
  - scope:
      type: posts
    values:
      # https://applause-button.com/
      applause_button: true