domain: example.com
url: https://example.com

title: Muhash
email: wind@example.com
author: Muhammed Ashfar

lang: en
baseurl: ''

plugins:
  - jekyll-seo-tag

# disqus:
#   shortname: example-com
#
rrss:
 # discord: ''
 # facebook: hola
 twitter: Hola
 instagram: Hola
 # linkedin: ''
 # pinterest: ''
 whatsapp: 123
 # telegram: ''
 email: muhammedashfar@hotmail.com
