# Domain
domain: https://muhashfar.github.io/PersonalPortfolio
url: https://muhashfar.github.io/PersonalPortfolio

# Info
title: Muhash
email: muhammedashfar@hotmail.com
author: Muhammed Ashfar

# Language
lang: en

# Baseurl
baseurl: ''

# Collections
collections:
  posts:
    output: true
    permalink: /:title
  feeds:
    output: true


plugins:
  - jekyll-seo-tag

# disqus:
#   shortname: example-com


# Menu
menu:
  - title: 'Home'
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>'
    url: '/'
  - title: 'Feed'
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>'
    url: '/feed'
  - title: 'Search'
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>'
    url: '/search'


rrss:
 # discord: ''
 # facebook: hola
 twitter: 'https://twitter.com/_muhash'
 instagram: 'https://www.instagram.com/_muhash/'
 # linkedin: ''
 # pinterest: ''
 whatsapp: 'https://wa.me/919496659631?text=hey%20%3A)%0A'
 # telegram: ''
 email: muhammedashfar@hotmail.com

defaults:
  # You can use the following to enable comments on all posts.
  - scope:
      type: posts
    values:
      # https://applause-button.com/
      applause_button: true