backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true

logo_url: https://muhahportfolio.netlify.app/assets/images/logo.png
site_url: https://muhash.site/

media_folder: "uploads"
collections:
  - label: "Global Site Settings"
    name: "site_config"
    editor:
      preview: false
    delete: true
    files:
      - label: "Metadata"
        name: "metadata"
        file: "_config.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: true
            hint: "Ex. My Website"
          - label: "E-mail"
            name: "email"
            widget: "string"
            required: true
            hint: "Ex. johndoe@example.com"
          - label: "Description"
            name: "description"
            widget: "text"
            required: true
            hint: "This keywords will be appeared on search engines."
      - label: "Graphic resources"
        name: "graphic_resources"
        file: "_data/resources.yml"
        fields:
          - label: "Logo"
            name: "logo"
            widget: "image"
            media_folder: /uploads/images
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "Ex. My Website"
          - label: "Top Bar Colour"
            name: "accent_color"
            widget: "color"
            allowInput: true
            required: true
            hint: "*Use your accent colour."
          - label: "Favicon"
            name: "favicon"
            widget: "file"
            media_folder: /uploads/images
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "Ex. My Website"
          - label: "Header & Footer Background"
            name: "head_foot_background"
            widget: "image"
            media_folder: /uploads/images
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "*upload atleast 1280*720 images to get better results."
          - label: "Body Background"
            name: "body_background"
            widget: "image"
            media_folder: /uploads/images
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "*upload atleast 1280*720 images to get better results."
      - label: "Rule Book"
        name: "rule_book"
        file: "_data/rulebook.yml"
        fields:
          - label: "Upload Rule Book"
            name: "url_rulebook"
            widget: "file"
            media_folder: /uploads/files
            media_library:
              config:
                allow_multiple: false
                choose_url: true
  # Meta data
  - label: "Metadata"
    name: "metadata"
    file: "_data/metadata.yml"
    fields:
      # Title
      - label: "Title"
        name: "meta_title"
        widget: "string"
        required: true
        hint: "Name of the website"
      # Description
      - label: "Description"
        name: "meta_desc"
        widget: "text"
        required: true
        hint: "Description about website"
      # Site Author
      - label: "Site Author"
        name: "site_author"
        widget: "string"
        required: true
        hint: "Author of the website"
      # OG:image
      - label: "OG:image"
        name: "og_image"
        widget: "image"
        media_folder: /uploads/images/metadata
        choose_url: true
        media_library:
          config:
            multiple: false
            max_file_size: 100000000
        required: true
        # Twitter image
      - label: "Twitter image"
        name: "twitter_image"
        widget: "image"
        media_folder: /uploads/images/metadata
        choose_url: true
        media_library:
          config:
            multiple: false
            max_file_size: 100000000
        required: true
        hint: "Ex. My Website"
      # Site Tags
      - label: "Site Tags"
        name: "site_tags"
        widget: "List"
        required: true
        hint: "Each item sperated by comma."
      # Site Language
      - Label: "Site Language"
        name: "site_language"
        widget: "select"
        options:
          - { label: "English", value: "English" }
          - { label: "Malayalam", value: "Malayalam" }

  # ~ Posts Section
  - label: "Posts"
    name: "posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    extension: "md"
    fields:
      # Date of Publish
      - label: "Publish date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
      # Layout [Hidden]
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      # Title of the post
      - label: "Post title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex. My very first post."
      # Author of the post [Hidden]
      - label: "Author"
        name: "author"
        widget: "Hidden"
        default: "Muhammed Ashfar"
      # Post Image
      - Label: "Post image"
        name: "image"
        widget: "image"
        media_folder: /uploads/images/posts
        choose_url: true
        media_library:
          config:
            multiple: false
            max_file_size: 100000000
        required: true
      # Post Categories
      - label: "Categories"
        name: "categories"
        widget: "select"
        options:
          - { label: "Poster", value: "Poster" }
          - { label: "Calligaphy", value: "Calligraphy" }
          - { label: "Magazine Cover", value: "Magazine Cover" }
          - { label: "Project36", value: "Project36" }
          - { label: "Logo", value: "Logo" }
        hint: "Ex. Calligraphy, Poster, Magazine Cover etc"
      # Post tags
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Each tag should be seperated by comma."
      # Post Description
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
      # Post Content
      - label: "Post Content"
        name: "body"
        widget: "markdown"
            