backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true

logo_url: https://muhash.netlify.app/assets/images/logo.png
site_url: https://muhash.site/

# Media Folder
media_folder: "uploads"

# Collections
collections:
  # Global Site Settings
  - label: "Global Site Settings"
    name: "site_config"
    editor:
      preview: false
    delete: true
    # Files
    files:
      # Site Info
      - label: "Site Info"
        name: "site_info"
        file: "_config.yml"
        fields:
          # Domain
          - label: "Doamin"
            name: "domain"
            widget: "string"
            required: true
          - label: "URL"
            name: "url"
            widget: "string"
            required: true
          # Info
          - label: "Title"
            name: "title"
            widget: "string"
            required: true
          # Email
          - label: "Email"
            name: "email"
            widget: "string"
          # Author
          - label: "Author"
            name: "author"
            widget: "string"
          # Baseurl
          - label: "Baseurl"
            name: "baseurl"
            widget: "string"
            required: true
          # Language
          - label: "Language"
            name: "lang"
            widget: "string"
            required: true

      # Meta data
      - label: "Metadata"
        name: "metadata"
        file: "_data/metadata.yml"
        fields:
          # Title
          - label: "Title"
            name: "meta_title"
            widget: "string"
            required: true
            hint: "Name of the website"
          # Description
          - label: "Description"
            name: "meta_desc"
            widget: "text"
            required: true
            hint: "Description about website"
          # Site Author
          - label: "Site Author"
            name: "site_author"
            widget: "string"
            required: true
            hint: "Author of the website"
          # OG:image
          - label: "OG:image"
            name: "og_image"
            widget: "image"
            media_folder: /uploads/images/metadata
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
          # Twitter image
          - label: "Twitter image"
            name: "twitter_image"
            widget: "image"
            media_folder: /uploads/images/metadata
            choose_url: true
            media_library:
              config:
                multiple: false
                max_file_size: 100000000
            required: true
            hint: "Ex. My Website"
          # Site Tags
          - label: "Site Tags"
            name: "site_tags"
            widget: "select"
            required: true
            multiple: true
            options: ["Art", "Calligraphy", "Poster", "Logo", "Magazine Cover", "Modern", "Flyer", "Illustration", "Nature", "Procreate"]
          # Site Language
          - Label: "Site Language"
            name: "site_language"
            widget: "select"
            multiple: true
            options:
              - { label: "English", value: "English" }
              - { label: "Malayalam", value: "Malayalam" }

  # ~ Posts Section
  - label: "Posts"
    name: "posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    extension: "md"
    fields:
      # Date of Publish
      - label: "Publish date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
      # Layout [Hidden]
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      # Title of the post
      - label: "Post title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex. My very first post."
      # Author of the post [Hidden]
      - label: "Author"
        name: "author"
        widget: "Hidden"
        default: "Muhammed Ashfar"
      # Post Image
      - Label: "Post image"
        name: "image"
        widget: "image"
        media_folder: /uploads/images/posts
        choose_url: true
        media_library:
          config:
            multiple: false
            max_file_size: 100000000
        required: true
      # Post Categories
      - label: "Categories"
        name: "category"
        widget: "select"
        options:
          - { label: "Poster", value: "Poster" }
          - { label: "Calligaphy", value: "Calligraphy" }
          - { label: "Magazine Cover", value: "Magazine Cover" }
          - { label: "Project36", value: "Project36" }
          - { label: "Logo", value: "Logo" }
        hint: "Ex. Calligraphy, Poster, Magazine Cover etc"
      # Post tags
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Each tag should be seperated by comma."
      # Post Description
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
      # Post Content
      - label: "Post Content"
        name: "body"
        widget: "markdown"
            